name: Docker

on:
  push:
  pull_request:
    
jobs:
  build_publish_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.2.0
        with:
          submodules: recursive

      - name: Build/push
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: ghcr.io
          image_name: "newSid2024/AudioTaggerv2"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
